### PR TITLE
[docs] add docs for 9.6.0 and 9.5.1

### PR DESCRIPTION
**Pull request by tobrun**
Add javadoc for v9.6.0 and 9.5.1

### CODE REVIEW

**Comment by Chaoba** [comment]
Why add doc to this repo? I believe should add to doc repo

**Review by colleenmcginnis — COMMENTED** [review]
The docs look ok. I don't know why the build is failing and I don't have access to circle. Maybe one of your teammates can review and approve?

**Comment by tobrun** [comment]
> Why add doc to this repo? I believe should add to doc repo

That has recently changed, we are now hosting them in 
https://github.com/mapbox/mapbox-gl-native-android/tree/publisher-production

> I don't know why the build is failing 

Because publish-production branch doesn't have circle-ci config

**Comment by kiryldz** [comment]
@tobrun - opened `README.md` in `publisher-production` branch.
```
In addition to deploying documentation from this repo, you may also need to update version constants in https://github.com/mapbox/android-docs/ and https://github.com/mapbox/help/.
```
Do we need to do it? And is it possible to add circle ci config to `publisher-production` if docs will be added in future or does it not matter?

**Comment by tobrun** [comment]
> Do we need to do it? 

@kiryldz yes, that PR is in https://github.com/mapbox/android-docs/pull/1567 

>  And is it possible to add circle ci config to publisher-production if docs will be added in future or does it not matter?

Would be cool but considering lifetime of this project, not worth it :)

**Comment by bomturbo** [comment]
#622

**Review by pengdev — APPROVED** [review]

**Pull request merged**
